// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/6/2025, 12:57:10 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Vili/Desktop/boggle/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/boggle/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/boggle/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/boggle/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/boggle/plugins/**/*.{js,ts,mjs}","C:/Users/Vili/Desktop/boggle/composables/**/*.{js,ts,mjs}","C:/Users/Vili/Desktop/boggle/utils/**/*.{js,ts,mjs}","C:/Users/Vili/Desktop/boggle/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/boggle/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/boggle/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/boggle/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;